"parameters":
  "bucket": "in.c-ex-xero-main"
  "consumer_key": "W2BUKSSGQZDVHDK2EYTTYNK79DT5JZ"
  "#consumer_secret": "I03PHQBD6DMPB47FIRD4ROAEPD1EQN"

  "debug": 1

  "#private_key": "-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQDKWDsrFegpbUx4d5EsXdGjnHBNp87hAO6U+qyPszlBd3Sa4uAY\n06fyTMrNt4dBOWM123HAdzGfveWz8poX5SISWV1/R6ErNCNGoPJao7o4F0o8/oNP\nQaZln5/elWeAaRhqdr+OiQ4K8bIjQMRq2JnkBym7a2RnXxPmlamntWV9GQIDAQAB\nAoGBAIneYEJVJODFNiuG3IWsTyD5gJOI2S76IZWkz1sCNOrkZ7D5ENQZsv8nT6+n\ncyL/5RdXNER9cnRzQUXA8TmCyBkdxs151NDamzesgiAinh0W28gxfKqJWb+Z0gxU\nlV0zL4Zy6HpsOW+321YktsYi/kQ9xYLaLy6SRODExZ3q244BAkEA8ilpgh/zltWT\nnCzjbPJHy5/Yf01YZEMyp+Qq0qs2JIYjgCCsgmifz39mrqznOZnGrl1nG4yOI1ij\nS5Ah3xFc4QJBANXoVXj9qiO60asteyGOXq8du98eUkhaAml0U2uVrI/r38dmCeOV\nidrZ4CYxLncEM24XggdAiirYZz+m6rNKrzkCQGJbtbIXvj3GlAT8KoemxMiNLUdP\nqBZZQOr2fvpAdmZRYXv6SXdSfY6vJYrPSb+YmR1bbLTA2z66EuFvMoLDL6ECQHyj\nqyIb1IaLNd6jWqrb1Sn+jljcxx8na15dDLqUdP9LdpIuT7bPjIr8BxLZ93Qb+4e7\npOVq4tdCTy8UqI8eBmkCQBeUBOx4KFwUdLV6Z+0hkumLpnnTbvk5D1WNdOSZihzm\nC2amfGWONi+dklojiQgZKU4vf8+nASbbwi0+iSoAEEk=\n-----END RSA PRIVATE KEY-----\n"
  "public_key": "-----BEGIN CERTIFICATE-----\nMIICPTCCAaYCCQCiM4oKPKiQqjANBgkqhkiG9w0BAQsFADBjMQswCQYDVQQGEwJD\nUzEaMBgGA1UECAwRSmlob21vcmF2c2t5IEtyYWoxDTALBgNVBAcMBEJybm8xDjAM\nBgNVBAoMBU1laXJvMRkwFwYJKoZIhvcNAQkBFgp2QG1laXJvLmlvMB4XDTE4MTIw\nOTIwMzAxM1oXDTIzMTIwODIwMzAxM1owYzELMAkGA1UEBhMCQ1MxGjAYBgNVBAgM\nEUppaG9tb3JhdnNreSBLcmFqMQ0wCwYDVQQHDARCcm5vMQ4wDAYDVQQKDAVNZWly\nbzEZMBcGCSqGSIb3DQEJARYKdkBtZWlyby5pbzCBnzANBgkqhkiG9w0BAQEFAAOB\njQAwgYkCgYEAylg7KxXoKW1MeHeRLF3Ro5xwTafO4QDulPqsj7M5QXd0muLgGNOn\n8kzKzbeHQTljNdtxwHcxn73ls/KaF+UiElldf0ehKzQjRqDyWqO6OBdKPP6DT0Gm\nZZ+f3pVngGkYana/jokOCvGyI0DEatiZ5Acpu2tkZ18T5pWpp7VlfRkCAwEAATAN\nBgkqhkiG9w0BAQsFAAOBgQCsUjG+ffocxJj5UUBYsi+Zi1UzNXrFdMP8cemY2Muw\nwPltLma5+smZYuz9pjVBM1hdQIwnUWsd1i2n3SuBp4JrSHARNavOgYd/WiZ8RpiB\ngL+TWkBa+0C79BJtHaKg9tROB72B0MPNziH9+1CUf5vtZQ6UX22KqNgvosk9TQqo\n7w==\n-----END CERTIFICATE-----\n"
  "parameters": 
    "fromDate": "2017-01-01"
    "toDate": "today"
  
  "debug": true
  "endpoint":
    - "Overpayments" 
    # - "Journals":
      # - "where": "SourceType==\"CASHPAID\""
#    - "BankTransactions":
#      - "includeArchived": "true"
